name: CI

on:
  push:
    branches: main
    tags: v*
  pull_request:

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install dependencies
        run: task dep
      - name: Run linters
        run: task vet
      - name: Run tests
        run: task test
